# Generated by Django 4.2.10 on 2024-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Colour name'),
        ),
        migrations.AlterField(
            model_name='colour',
            name='paint_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Paint code'),
        ),
    ]
